// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw77DreLRhYSy6nNEL7VHZaN3Jz3u1l-Q',
    appId: '1:527704146673:web:4e47013ed2dea0e91b9f50',
    messagingSenderId: '527704146673',
    projectId: 'finalproject-1d57d',
    authDomain: 'finalproject-1d57d.firebaseapp.com',
    storageBucket: 'finalproject-1d57d.firebasestorage.app',
    measurementId: 'G-0PG7B1THWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATOJfLRbYU1burb8A6kIMhhgpFmT1cWl0',
    appId: '1:527704146673:android:c3f11648b8f77ca81b9f50',
    messagingSenderId: '527704146673',
    projectId: 'finalproject-1d57d',
    storageBucket: 'finalproject-1d57d.firebasestorage.app',
  );
}
